baseURL = "http://bradenlive.com/"
languageCode = "en-us"
title = "BradenLive"
theme = "ezhil"
paginate = 10
enableEmoji = true #I added this

copyright = "© 2019 | Braden Schrock"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-136283593-4"
disqusShortname = "bradenlive"

[params]
	subtitle = "Things I write live here"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "auto" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 5

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/braden-schrock"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://www.twitter.com/braden_live"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/arkanian86"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

# I added this param---------
[[params.logo]]
name = "logo"
icon = "logo"
url = "/images/helo.jpg"
# ---------------------------

[taxonomies]
   tag = "tags"
   category = "categories"
