---
title: Reflecting on my 2019 goals
author: Braden
date: '2020-01-03'
slug: reflecting-on-my-2019-goals
categories:
  - Reflection
tags:
  - goals
  - failure
  - metrics
  
draft: no

twitter:
  card: "summary"
  site: "@braden_live"
  title: Reflecting on my 2019 goals
  description: At the beginning of 2019, I set a number of goals for myself. Here's how I did.
  image: 'https://www.bradenlive.com/posts/'
---

I've never been one for New Year's Resolutions. I always thought the entire process was artificial -- why make resolutions based upon an arbitrary number from the calendar?

I held this view up until last year, when my wife convinced me to come along with her for her "end-of-year reflection"...a few hours at our local coffee shop ([Colectivo](https://colectivocoffee.com/cafes/evanston) in Evanston, if you're wondering). We spent the time thinking about everything that happened in the past year (2018) including a Navy deployment for me, medical issues for her, and starting school at Kellogg. Each of us also thought about how we wanted to shape the coming year, and wrote down our goals. It was a useful exercise -- we repeated it this year.

Looking back at what I wrote a year ago has been illuminating. Over the course of 2019, the goals I set were never completely out of mind, but I also never deliberately looked back at my journal to see precisely what I had written or how I had progressed in completing the goals, and my impression from memory was that I was nowhere close to completing any of them. Today, however, I was surprised to find that I actually completed a several of them, and made significant progress on even more.

I encourage everyone to complete an end-of-year reflection, in whatever format works best. 

***

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(ggridges)

type <- c('daily', 'daily', 'habit', 'habit', 'habit', 'seasonal', 'seasonal', 'year-long', 'year-long', 'year-long', 'year-long', 'year-long')
status <- factor(c('complete', 'incomplete', 'push', 'push', 'incomplete', 'complete', 'complete', 'complete', 'complete', 'push', 'push', 'incomplete'), levels = c('complete', 'push', 'incomplete'))

results <- data.frame(type, status)

# ggplot(results, aes(x = type)) +
#   geom_bar(aes(fill = status))

# this works ------------------------------------
ggplot(results, aes(x = status)) +
  geom_dotplot(aes(fill = status), binwidth = .2) +
  facet_grid(vars(type)) +
  theme_minimal() +
  theme(panel.background = element_rect(fill = NA, color = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.spacing = unit(0, "lines"),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "none",
        strip.text.y = element_text(angle = 360)) +
  scale_fill_manual(values=c("#66a182", "#8d96a3", "#d1495b"))
# ------------------------------------------------

# ggplot(results) +
#   geom_dotplot(aes(x = status, fill = type), binwidth = .2) +
#   facet_grid(vars(type)) +
#   theme_minimal()
# 
# ggplot(results, aes(x = status, y = type)) +
#   geom_point() +
#   facet_grid(type ~ ., switch = "both")
# 
# library(waffle)
# ggplot(results, aes(fill=type, values=as.integer(status) )) +
#   geom_waffle(color = "white", size=1.125, n_rows = 3, flip = TRUE) +
#   facet_wrap(status~type) +
#   coord_equal() +
#   scale_x_discrete(expand=c(0,1)) +
#   scale_y_discrete(expand=c(0,1))
# 
ggplot(results, aes(fill=type, values=sum(as.integer(status)) )) +
  geom_waffle() +
  facet_wrap(status~type) +
  coord_equal()
# 
# ggplot(results) +
#   geom_dotplot(aes(x=status, y=type), binwidth=.2) +
#   facet_grid(vars(type))
# 
# ggplot(results) + 
#   geom_histogram(aes(x=status), stat = "count") +
#   facet_grid(status~type)

rows <- 2
cols <- 2

results %>%
  arrange(status, type) %>%
  group_by(status, type) %>%
  mutate(num = row_number(),
         x_pos = (num - 1) %/% rows,
         y_pos = rows - (num - 1) %% rows - 1) %>%

  ggplot(aes(x = x_pos, y = y_pos, fill = status)) +
  geom_tile(color = "white") +
  coord_equal(xlim = c(0, cols) - 0.5,
              ylim = c(0, rows) - 0.5) +
  facet_grid(vars(type), vars(status)) +
  theme_light() +
  theme(panel.grid = element_blank(),
        panel.spacing = unit(0, "lines"),
        axis.text = element_blank(),
        strip.text.y = element_text(angle = 360),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank()) +
  scale_fill_manual(values=c("#66a182", "#8d96a3", "#d1495b"))
```

I divided 12 goals for the year into four categories based on how often I would have to think about them:

* **Daily:** goals where I would need to complete a task every single day
* **Habit:** goals where I would need to complete a task a few times every week
* **Seasonal:** goals that were related to a specific time of the year
* **Year-long:** long-term goals that might require sporadic effort throughout the year











